### PR TITLE
update instructions

### LINKED ISSUE #5: Instructions for installing the latest version of Angular missing
The first objective reads:

`Download the latest version of Angular 1.x`

But no instructions are provided. Also at the end of the lesson, students are asked to visit `index.html` without instructions on how to start the app:

``````
Next, we need to tell Angular about our controller. Add this to the bottom of MainController.js:

angular
  .module('app')
  .controller('MainController', MainController);
HELLO, YOUR NAME!

Now open up index.html in Google Chrome and you should see Hello, your name! Wow - our first small Angular application. ```
``````

### PR DESCRIPTION
**Pull request by ipc103**
fixes #5 - @PeterBell @aturkewi could I get some :eyes: on this PR?

### CODE REVIEW

**Comment by PeterBell** [comment]
Hey @ipc103 looks good to me. Just to be clear, have we got people set up with a python installation at some point earlier in the curriculum? Other than that, LGTM :+1: to merge...

**Comment by ipc103** [comment]
Don't think we ever have the students install python. The assumptions I'm
making are:
1. Any student using a Mac will have a python installation already
2. Nitrous users will also have a python installation -
   https://community.nitrous.io/docs/preview-a-static-html-page

Are those fair assumptions to make?

On Tue, Mar 22, 2016 at 10:55 AM, Peter Bell notifications@github.com
wrote:

> Hey @ipc103 https://github.com/ipc103 looks good to me. Just to be
> clear, have we got people set up with a python installation at some point
> earlier in the curriculum? Other than that, LGTM [image: :+1:] to merge...
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/learn-co-curriculum/angular-project-setup-lab/pull/6#issuecomment-199852075

## 

```
 Ian Candy
 Web Instructor
```

**Comment by PeterBell** [comment]
Hey @ipc103 let's :ship: it and see. Assumptions always scare me, but this is as good a time to figure it out as any. Just to ask, is python installed on the usb sticks we're sending out to people? As long as it's there as well, I'm :+1: to this

**Comment by ipc103** [comment]
yes, it's included in the ubuntu distribution as well (thanks @loganhasson ) - going to merge!

**Comment by PeterBell** [comment]
Awesome - thanks @ipc103 !

**Pull request merged**
